name: Deploy Child Theme to Plesk via FTPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy Child Theme via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          security: explicit
          passive: true
          tlsReuse: false
          timeout: 60000
          port: 21

          local-dir: ./
          server-dir: /httpdocs/wp-content/themes/twentytwentythree-child/

          exclude: |
            .git*
            .github/
            node_modules/
